services:
  gfw-defense:
    image: pexcn/docker-images:gfw-defense
    container_name: gfw-defense
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Taipei
      BLOCKING_POLICY: DROP
      PASSING_POLICY: ACCEPT
      DEFAULT_POLICY: RETURN
      QUICK_MODE: 0
      PREFER_BLACKLIST: 0
      ALLOW_RESERVED_ADDRESS: 1
      USE_IPTABLES_NFT_BACKEND: 0
      BLACKLIST_FILES: /etc/gfw-defense/blacklist.txt,/etc/gfw-defense/chnroute.txt
      WHITELIST_FILES: /etc/gfw-defense/whitelist.txt,/etc/gfw-defense/440100.txt
      UPDATE_LIST_INTERVAL: 86400
      UPDATE_LIST_URLS: https://raw.githubusercontent.com/pexcn/daily/gh-pages/chnroute/chnroute.txt,https://raw.githubusercontent.com/metowolf/iplist/master/data/cncity/440100.txt
    volumes:
      - ./gfw-defense-data:/etc/gfw-defense
